# Generated by Django 5.1.5 on 2025-01-29 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_id_user_guid_user_role_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+9989' and be followed by 8 digits.", regex='^\\+9989\\d{9}$')]),
        ),
    ]
